In [ ]:
!pip install ucimlrepo pandas numpy scikit-learn matplotlib

In [6]:
# 数据集导入，并将 y 设置为 0/1 值  后续封装为 load_data 函数
from ucimlrepo import fetch_ucirepo 
import numpy as np

# fetch dataset 
sonar = fetch_ucirepo(id=151) 
  
# data (as pandas dataframes) 
X = sonar.data.features 
y = sonar.data.targets 
X.head()
y.head()
y_c = np.unique(y)
y = np.array(y)
for i in range(len(y_c)):
    y[y == y_c[i]] = i
y = y.astype(int)

In [2]:
print(y_c, '\n',y)

['M' 'R'] 
 [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0

In [2]:
# 测试数据切分是否正常

from utils import random_split, k_fold_cross_validation, leave_one_out_cross_validation

X_train, X_test, y_train, y_test = k_fold_cross_validation(X, y, 5)
print(f'k_fold_cross_validation: {X_train.shape}, {X_test.shape}, {y_train.shape}, {y_test.shape}')

X_train, X_test, y_train, y_test = leave_one_out_cross_validation(X, y)
print(f'leave_one_out_cross_validation: {X_train.shape}, {X_test.shape}, {y_train.shape}, {y_test.shape}')

X_train, X_test, y_train, y_test = random_split(X, y, 0.3)
print(f'random_split: {X_train.shape}, {X_test.shape}, {y_train.shape}, {y_test.shape}')

k_fold_cross_validation: (167, 60), (41, 60), (167, 1), (41, 1)
leave_one_out_cross_validation: (207, 60), (1, 60), (207, 1), (1, 1)
random_split: (145, 60), (63, 60), (145, 1), (63, 1)


In [5]:
# X_train[0:3,:2]
np.mean(X_test[1,:])
cov_m = np.zeros(X_test[1,:].shape[0])
np.mean(X_test,axis=0).shape
np.cov(X_test.T).shape


array([   9.85291837,   13.91528594,  -28.49420217,   23.88164391,
         -1.48449585,   -3.38461824,   -2.41717141,  -10.36275757,
          8.48741066,   -1.87055107,    0.3503974 ,    4.62850243,
          8.0712496 ,   -2.36112895,    1.05290153,   -0.26922331,
        -10.81153439,   11.44736519,   -4.84416734,    3.97670198,
         -4.69482121,    7.13861357,   -6.45080804,    9.37857195,
         -4.97628065,   -2.38393811,    4.22247314,   -1.67921765,
         -1.66607956,    8.29067496,  -14.6780713 ,   11.1227271 ,
         -4.41726343,   -4.32054055,    8.90883885,   -6.39181502,
         -0.73085779,   -0.45171624,    4.7879488 ,   -4.63749772,
          4.97107301,   -6.10850118,    6.45473754,   -3.68378809,
          1.64023974,   -2.41374896,    9.63242842,    4.28353446,
         24.31740735,  -44.72937524,  -25.0832603 ,   32.55320885,
         51.25159363,   39.61450524, -106.40022208,  -23.06211665,
         53.10212203,   41.73883413,   38.41447393,  -58.88992

In [4]:
from utils import *
W, u1, u2 = fisher_discriminant_analysis(X_train, y_train)
y_pred = np.zeros(len(y_test))
for i in range(len(y_test)):
    y_pred[i] = judge_sample(X_test[i,:], W, u1, u2)
print("len(y_test):", len(y_test))
count = 0
for i in range(len(y_test)):
    # print(f"y_pred[i]:{y_pred[i]}, y_test[i]:{y_test[i]}")
    # print(y_pred[i] == y_test[i])
    if y_pred[i] == y_test[i]:
        count+=1
print("count:", count)
accuracy = count / len(y_test)
print("accuracy:", accuracy)

len(y_test): 63
count: 45
accuracy: 0.7142857142857143


In [27]:
y_test
W

array([-5.02732189e+13,  2.85425258e+12, -2.04736785e+12, -1.20918418e+12,
       -5.67547689e+11, -1.66496288e+11,  4.26959260e+11, -4.21257668e+12,
        9.13392888e+11, -8.94838500e+11, -1.02919094e+12,  5.18496695e+12,
        1.78190525e+12, -1.65684709e+12,  1.07896784e+12,  2.58500777e+12,
        3.02741365e+11,  1.49890795e+12, -3.23973244e+12,  5.77306652e+11,
        2.55351218e+12,  2.70615206e+11, -3.40955687e+11, -1.77194919e+12,
        5.01047589e+11, -8.85005790e+11, -2.25006924e+10,  2.52595909e+12,
        4.25269821e+12,  1.02215028e+11, -8.50023886e+10, -1.10629632e+12,
       -8.21590014e+10, -3.63809132e+12, -3.65358513e+12, -2.35739869e+12,
        1.03529306e+12,  9.39417299e+10,  7.39624705e+11, -8.12166267e+11,
        2.55200722e+12,  1.48629182e+12,  9.34577898e+10,  3.96536269e+12,
       -3.43720285e+12, -1.76070176e+12, -1.42757683e+12, -1.86152733e+12,
        1.24927801e+11, -2.25982160e+11, -4.46464783e+11, -3.99772688e+11,
       -3.84485191e+11,  

In [152]:
def judge_sample(sample, w, u1, u2):
    # sample 属于 c1 返回 False，属于 c2 返回 True
    center_1 = np.dot(w.T, u1)
    center_2 = np.dot(w.T, u2)
    pos = np.dot(w.T, sample)
    return abs(pos - center_1) > abs(pos - center_2)

In [ ]:
W = fisher_discriminant_analysis(X_train, y_train)
index1 = np.array(y[y['class'] == 0].index) # 获取类别为'0'的 index
index2 = np.array(y[y['class'] == 1].index) # 获取类别为'1'的 index
_, u1 = cal_cov_and_avg(X.iloc[index1])
_, u2 = cal_cov_and_avg(X.iloc[index2])
y_pred = np.zeros(len(y_test))
for i in range(len(y_test)):
    y_pred[i] = judge_sample(X_test.to_numpy()[i], W, u1, u2)
accuracy = np.sum(y_pred == y_test) / len(y_test)
print("accuracy:", accuracy)

In [ ]:
len(y_test)

In [ ]:
np.dot(W.T, u1)
np.dot(W.T, u2)
pos = np.dot(W.T, X_test.to_numpy()[0])
pos
pos - np.dot(W.T, u1)
res = judge_sample(X_test.to_numpy()[0], W, u1, u2)
res

In [205]:
def fisher_discriminant_analysis(X, y):
    index1 = np.where(y == 0)[0] # 获取类别为'0'的 index
    index2 = np.where(y == 1)[0] # 获取类别为'1'的 index
    con_1, u1 = cal_cov_and_avg(X.iloc[index1])
    con_2, u2 = cal_cov_and_avg(X.iloc[index2])
    S_W = con_1 + con_2
    u, s, v = np.linalg.svd(S_W)
    # 投影方向向量wß
    S_W_inv = np.dot(np.dot(v.T, np.linalg.inv(np.diag(s))), u.T)
    W = np.dot(S_W_inv,u1 - u2)
    return W



W = fisher_discriminant_analysis(X_train, y_train)
index1 = np.where(y_train == 0)[0] # 获取类别为'0'的 index
index2 = np.where(y_train == 1)[0] # 获取类别为'1'的 index
_, u1 = cal_cov_and_avg(X_train.iloc[index1])
_, u2 = cal_cov_and_avg(X_train.iloc[index2])
# y_pred = np.zeros(len(y_test))
# for i in range(len(y_test)):
#     y_pred[i] = judge_sample(X_test.to_numpy()[i], W, u1, u2)
# accuracy = np.sum(y_pred == y_test) / len(y_test)
# print("accuracy:", accuracy)

In [ ]:
def k_fold_cross_validation(X, y, n_splits, random_state=42):
    X.to_numpy()
    y.to_numpy()
    skf = StratifiedKFold(n_splits=n_splits,random_state=random_state,shuffle=True)
    skf.get_n_splits(X,y)
    for _, (train_index, test_index) in enumerate(skf.split(X,y)):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = k_fold_cross_validation(X, y,n_splits=3, random_state=42)

In [ ]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
skf.get_n_splits(X, y)
for _, (train_index, test_index) in enumerate(skf.split(X, y)):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [ ]:
X, y = load_data('sonar')
y_c = np.unique(y)
X.to_numpy()
y = np.array(y)
for i in range(len(y_c)):
    y[y == y_c[i]] = i
y = y.astype(int)

In [ ]:
type(y)
type(X.values)